from __future__ import annotations

import os
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any

try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
except ImportError:  # pragma: no cover
    psycopg2 = None
    RealDictCursor = None

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / 'data' / 'odt_tracker.db'
DB_PATH.parent.mkdir(parents=True, exist_ok=True)
DATABASE_URL = os.getenv('DATABASE_URL')


def is_postgres() -> bool:
    return bool(DATABASE_URL)


class _PgConn:
    """Wraps psycopg2 connection so conn.execute() works like sqlite3."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, query, params=None):
        cur = self._conn.cursor()
        if params is not None:
            cur.execute(query, params)
        else:
            cur.execute(query)
        return cur

    def cursor(self):
        return self._conn.cursor()

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is None:
            self._conn.commit()
        else:
            self._conn.rollback()
        self._conn.close()


def get_connection():
    if is_postgres():
        if psycopg2 is None:
            raise RuntimeError('DATABASE_URL is set, but psycopg2 is not installed. Install psycopg2-binary.')
        conn = psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)
        conn.autocommit = False
        return _PgConn(conn)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def create_game(name: str | None = None) -> int:
    now = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S')
    game_name = name or f'Game {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")}'

    with get_connection() as conn:
        if is_postgres():
            cursor = conn.cursor()
            cursor.execute(
                'INSERT INTO games (name, created_at) VALUES (%s, %s) RETURNING id',
                (game_name, now),
            )
            game_id = int(cursor.fetchone()['id'])
            cursor.execute(
                'INSERT INTO settings (key, value) VALUES (%s, %s) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value',
                ('current_game_id', str(game_id)),
            )
        else:
            cursor = conn.execute(
                'INSERT INTO games (name, created_at) VALUES (?, ?)',
                (game_name, now),
            )
            game_id = int(cursor.lastrowid)
            conn.execute(
                'INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value',
                ('current_game_id', str(game_id)),
            )

        return game_id


def get_current_game_id() -> int:
    with get_connection() as conn:
        if is_postgres():
            row = conn.execute('SELECT value FROM settings WHERE key = %s', ('current_game_id',)).fetchone()
        else:
            row = conn.execute('SELECT value FROM settings WHERE key = ?', ('current_game_id',)).fetchone()

        if row is None:
            return create_game()
        return int(row['value'])


def set_current_game_id(game_id: int) -> None:
    with get_connection() as conn:
        if is_postgres():
            exists = conn.execute('SELECT 1 FROM games WHERE id = %s', (game_id,)).fetchone()
            if exists is None:
                raise ValueError(f'Game not found: {game_id}')
            conn.execute(
                'INSERT INTO settings (key, value) VALUES (%s, %s) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value',
                ('current_game_id', str(game_id)),
            )
        else:
            exists = conn.execute('SELECT 1 FROM games WHERE id = ?', (game_id,)).fetchone()
            if exists is None:
                raise ValueError(f'Game not found: {game_id}')
            conn.execute(
                'INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value',
                ('current_game_id', str(game_id)),
            )


def init_db() -> None:
    migrate_legacy_schema()

    with get_connection() as conn:
        if is_postgres():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS games (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS settings (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS teams (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    game_id INTEGER NOT NULL,
                    name TEXT NOT NULL,
                    UNIQUE(game_id, name),
                    FOREIGN KEY(game_id) REFERENCES games(id)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS participants (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    game_id INTEGER NOT NULL,
                    name TEXT NOT NULL,
                    team_id INTEGER NOT NULL,
                    weight_kg DOUBLE PRECISION NOT NULL,
                    arrival_time TEXT,
                    UNIQUE(game_id, name),
                    FOREIGN KEY(game_id) REFERENCES games(id),
                    FOREIGN KEY(team_id) REFERENCES teams(id)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS drinks (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    game_id INTEGER NOT NULL,
                    participant_id INTEGER NOT NULL,
                    timestamp TEXT NOT NULL,
                    beverage TEXT NOT NULL,
                    volume_ml DOUBLE PRECISION NOT NULL,
                    abv_percent DOUBLE PRECISION NOT NULL,
                    FOREIGN KEY(game_id) REFERENCES games(id),
                    FOREIGN KEY(participant_id) REFERENCES participants(id)
                )
                """
            )
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS games (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS settings (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS teams (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    game_id INTEGER NOT NULL,
                    name TEXT NOT NULL,
                    UNIQUE(game_id, name),
                    FOREIGN KEY(game_id) REFERENCES games(id)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS participants (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    game_id INTEGER NOT NULL,
                    name TEXT NOT NULL,
                    team_id INTEGER NOT NULL,
                    weight_kg REAL NOT NULL,
                    arrival_time TEXT,
                    UNIQUE(game_id, name),
                    FOREIGN KEY(game_id) REFERENCES games(id),
                    FOREIGN KEY(team_id) REFERENCES teams(id)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS drinks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    game_id INTEGER NOT NULL,
                    participant_id INTEGER NOT NULL,
                    timestamp TEXT NOT NULL,
                    beverage TEXT NOT NULL,
                    volume_ml REAL NOT NULL,
                    abv_percent REAL NOT NULL,
                    FOREIGN KEY(game_id) REFERENCES games(id),
                    FOREIGN KEY(participant_id) REFERENCES participants(id)
                )
                """
            )

    if get_current_game_id() is None:
        create_game('Game 1')

def ensure_seed_data():
    with get_connection() as conn:
        if is_postgres():
            game_count = conn.execute('SELECT COUNT(*) AS count FROM games').fetchone()['count']
        else:
            game_count = conn.execute('SELECT COUNT(*) AS count FROM games').fetchone()['count']

        if game_count == 0:
            game_id = create_game('Game 1')
        else:
            game_id = get_current_game_id()

        if is_postgres():
            team_count = conn.execute('SELECT COUNT(*) AS count FROM teams WHERE game_id = %s', (game_id,)).fetchone()['count']
        else:
            team_count = conn.execute('SELECT COUNT(*) AS count FROM teams WHERE game_id = ?', (game_id,)).fetchone()['count']

        teams = ['Team 1', 'Team 2', 'Team 3']
        for name in teams:
            if is_postgres():
                conn.execute('INSERT INTO teams (game_id, name) VALUES (%s, %s)', (game_id, name))
            else:
                conn.execute('INSERT INTO teams (game_id, name) VALUES (?, ?)', (game_id, name))

        participants = [
            ('Ale', 1, 72.0, '2025-11-01T18:02:00'),
            ('Arvid', 2, 78.0, '2025-11-01T18:00:00'),
            ('Calle', 3, 73.0, '2025-11-01T18:00:00'),
            ('Edmund', 1, 72.0, '2025-11-01T18:00:00'),
            ('Felu', 2, 81.0, '2025-11-01T18:02:00'),
            ('HEDman', 3, 93.0, '2025-11-01T18:10:00'),
            ('HELLman', 1, 91.0, '2025-11-01T19:30:00'),
            ('Jappe', 3, 71.0, '2025-11-01T18:00:00'),
            ('Nisse', 1, 70.0, '2025-11-01T18:00:00'),
            ('Otki', 2, 72.0, '2025-11-01T18:00:00'),
            ('Robin', 3, 80.0, '2025-11-01T18:05:00'),
            ('Vicke', 1, 72.0, '2025-11-01T18:00:00'),
            ('Ville', 2, 80.0, '2025-11-01T18:05:00'),
        ]

        for name, team_index, weight_kg, arrival in participants:
            if is_postgres():
                team_id = conn.execute(
                    'SELECT id FROM teams WHERE game_id = %s AND name = %s',
                    (game_id, f'Team {team_index}'),
                ).fetchone()['id']
                conn.execute(
                    'INSERT INTO participants (game_id, name, team_id, weight_kg, arrival_time) VALUES (%s, %s, %s, %s, %s)',
                    (game_id, name, team_id, weight_kg, arrival),
                )
            else:
                team_id = conn.execute(
                    'SELECT id FROM teams WHERE game_id = ? AND name = ?',
                    (game_id, f'Team {team_index}'),
                ).fetchone()['id']
                conn.execute(
                    'INSERT INTO participants (game_id, name, team_id, weight_kg, arrival_time) VALUES (?, ?, ?, ?, ?)',
                    (game_id, name, team_id, weight_kg, arrival),
                )

        if is_postgres():
            participant_rows = conn.execute('SELECT id, name FROM participants WHERE game_id = %s', (game_id,)).fetchall()
        else:
            participant_rows = conn.execute('SELECT id, name FROM participants WHERE game_id = ?', (game_id,)).fetchall()
        participant_lookup = {row['name']: row['id'] for row in participant_rows}

        demo_drinks = [
            ('Ale', 'Karhu', 330.0, 5.2, '2025-11-01T18:35:00'),
            ('Ale', 'Seltzer', 500.0, 4.7, '2025-11-01T19:35:00'),
            ('Arvid', 'Mariestad', 330.0, 4.8, '2025-11-01T18:40:00'),
            ('Arvid', 'Sandels', 330.0, 4.5, '2025-11-01T19:10:00'),
            ('Calle', 'Karhu', 500.0, 5.2, '2025-11-01T18:44:00'),
            ('Calle', 'Seltzer', 330.0, 4.7, '2025-11-01T19:50:00'),
            ('Edmund', 'Sandels', 500.0, 4.5, '2025-11-01T18:31:00'),
            ('Edmund', 'Karhu', 330.0, 5.2, '2025-11-01T19:20:00'),
            ('Felu', 'Karhu', 500.0, 5.2, '2025-11-01T18:36:00'),
            ('Felu', 'Seltzer', 330.0, 4.7, '2025-11-01T20:01:00'),
            ('HEDman', 'Sandels', 500.0, 4.5, '2025-11-01T18:57:00'),
            ('HEDman', 'Karhu', 330.0, 5.2, '2025-11-01T19:40:00'),
            ('HELLman', 'IPA', 330.0, 6.0, '2025-11-01T19:45:00'),
            ('Jappe', 'Pirkka', 250.0, 4.5, '2025-11-01T18:56:00'),
            ('Nisse', 'Sandels', 500.0, 4.5, '2025-11-01T18:41:00'),
            ('Nisse', 'Karhu', 500.0, 5.2, '2025-11-01T19:54:00'),
            ('Otki', 'Kupari', 330.0, 4.8, '2025-11-01T18:58:00'),
            ('Robin', 'Seltzer', 500.0, 4.7, '2025-11-01T19:13:00'),
            ('Robin', 'Sandels', 330.0, 4.5, '2025-11-01T20:15:00'),
            ('Vicke', 'Karhu', 500.0, 5.2, '2025-11-01T18:52:00'),
            ('Vicke', 'Sandels', 330.0, 4.5, '2025-11-01T19:49:00'),
            ('Ville', 'Karhu', 500.0, 5.2, '2025-11-01T18:39:00'),
            ('Ville', 'Seltzer', 330.0, 4.7, '2025-11-01T19:01:00'),
        ]

        for name, beverage, volume_ml, abv_percent, timestamp in demo_drinks:
            participant_id = participant_lookup[name]
            if is_postgres():
                conn.execute(
                    'INSERT INTO drinks (game_id, participant_id, timestamp, beverage, volume_ml, abv_percent) VALUES (%s, %s, %s, %s, %s, %s)',
                    (game_id, participant_id, timestamp, beverage, volume_ml, abv_percent),
                )
            else:
                conn.execute(
                    'INSERT INTO drinks (game_id, participant_id, timestamp, beverage, volume_ml, abv_percent) VALUES (?, ?, ?, ?, ?, ?)',
                    (game_id, participant_id, timestamp, beverage, volume_ml, abv_percent),
                )


def _serialize_row(row: sqlite3.Row | Any) -> dict[str, Any]:
    if row is None:
        return {}
    if isinstance(row, sqlite3.Row):
        return dict(row)
    if hasattr(row, '_asdict'):
        return row._asdict()
    return dict(row)


def list_teams() -> list[dict[str, Any]]:
    game_id = get_current_game_id()
    with get_connection() as conn:
        if is_postgres():
            rows = conn.execute('SELECT id, game_id, name FROM teams WHERE game_id = %s ORDER BY id', (game_id,)).fetchall()
        else:
            rows = conn.execute('SELECT id, game_id, name FROM teams WHERE game_id = ? ORDER BY id', (game_id,)).fetchall()
        return [_serialize_row(row) for row in rows]


def list_participants() -> list[dict[str, Any]]:
    game_id = get_current_game_id()
    with get_connection() as conn:
        if is_postgres():
            rows = conn.execute(
                '''
                SELECT p.id, p.game_id, p.name, p.team_id, t.name AS team_name, p.weight_kg, p.arrival_time
                FROM participants p
                JOIN teams t ON t.id = p.team_id
                WHERE p.game_id = %s
                ORDER BY p.name ASC
                ''',
                (game_id,),
            ).fetchall()
        else:
            rows = conn.execute(
                '''
                SELECT p.id, p.game_id, p.name, p.team_id, t.name AS team_name, p.weight_kg, p.arrival_time
                FROM participants p
                JOIN teams t ON t.id = p.team_id
                WHERE p.game_id = ?
                ORDER BY p.name ASC
                ''',
                (game_id,),
            ).fetchall()
        return [_serialize_row(row) for row in rows]


def get_participant_by_name(name: str) -> dict[str, Any] | None:
    game_id = get_current_game_id()
    with get_connection() as conn:
        if is_postgres():
            row = conn.execute(
                '''
                SELECT p.id, p.game_id, p.name, p.team_id, t.name AS team_name, p.weight_kg, p.arrival_time
                FROM participants p
                JOIN teams t ON t.id = p.team_id
                WHERE p.game_id = %s AND p.name = %s
                ''',
                (game_id, name),
            ).fetchone()
        else:
            row = conn.execute(
                '''
                SELECT p.id, p.game_id, p.name, p.team_id, t.name AS team_name, p.weight_kg, p.arrival_time
                FROM participants p
                JOIN teams t ON t.id = p.team_id
                WHERE p.game_id = ? AND p.name = ?
                ''',
                (game_id, name),
            ).fetchone()
        return None if row is None else _serialize_row(row)


def add_participant(name: str, team_name: str, weight_kg: float, arrival_time: str | None = None) -> dict[str, Any]:
    clean_name = str(name).strip()
    clean_team = str(team_name).strip() if team_name else 'Team 1'
    clean_weight = float(weight_kg)
    game_id = get_current_game_id()

    if arrival_time is None:
        arrival_time = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S')

    if not clean_name:
        raise ValueError('Participant name is required.')
    if clean_weight <= 0:
        raise ValueError('Weight must be greater than zero.')

    with get_connection() as conn:
        try:
            if is_postgres():
                team_row = conn.execute(
                    'SELECT id FROM teams WHERE game_id = %s AND name = %s',
                    (game_id, clean_team),
                ).fetchone()
                if team_row is None:
                    cursor = conn.cursor()
                    cursor.execute('INSERT INTO teams (game_id, name) VALUES (%s, %s) RETURNING id', (game_id, clean_team))
                    team_id = int(cursor.fetchone()['id'])
                else:
                    team_id = int(team_row['id'])

                cursor = conn.cursor()
                cursor.execute(
                    'INSERT INTO participants (game_id, name, team_id, weight_kg, arrival_time) VALUES (%s, %s, %s, %s, %s) RETURNING id',
                    (game_id, clean_name, team_id, clean_weight, arrival_time),
                )
                participant_id = int(cursor.fetchone()['id'])
            else:
                team_row = conn.execute('SELECT id FROM teams WHERE game_id = ? AND name = ?', (game_id, clean_team)).fetchone()
                if team_row is None:
                    cursor = conn.execute('INSERT INTO teams (game_id, name) VALUES (?, ?)', (game_id, clean_team))
                    team_id = cursor.lastrowid
                else:
                    team_id = team_row['id']

                cursor = conn.execute(
                    'INSERT INTO participants (game_id, name, team_id, weight_kg, arrival_time) VALUES (?, ?, ?, ?, ?)',
                    (game_id, clean_name, team_id, clean_weight, arrival_time),
                )
                participant_id = cursor.lastrowid
        except (sqlite3.IntegrityError, Exception) as exc:
            if is_postgres() and hasattr(exc, 'pgcode') and exc.pgcode == '23505':
                raise ValueError(f'Participant "{clean_name}" already exists in this game.') from exc
            if not is_postgres() and isinstance(exc, sqlite3.IntegrityError):
                raise ValueError(f'Participant "{clean_name}" already exists in this game.') from exc
            raise

        return {
            'id': participant_id,
            'game_id': game_id,
            'name': clean_name,
            'team_id': team_id,
            'team_name': clean_team,
            'weight_kg': float(clean_weight),
            'arrival_time': arrival_time,
        }


def add_drink(participant_name: str, beverage: str, volume_ml: float, abv_percent: float, timestamp: str | None = None) -> dict[str, Any]:
    participant = get_participant_by_name(participant_name)
    if participant is None:
        raise ValueError(f'Participant not found: {participant_name}')

    if timestamp is None:
        timestamp = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S')

    with get_connection() as conn:
        if is_postgres():
            cursor = conn.cursor()
            cursor.execute(
                'INSERT INTO drinks (game_id, participant_id, timestamp, beverage, volume_ml, abv_percent) VALUES (%s, %s, %s, %s, %s, %s) RETURNING id',
                (participant['game_id'], participant['id'], timestamp, beverage, float(volume_ml), float(abv_percent)),
            )
            drink_id = int(cursor.fetchone()['id'])
        else:
            cursor = conn.execute(
                'INSERT INTO drinks (game_id, participant_id, timestamp, beverage, volume_ml, abv_percent) VALUES (?, ?, ?, ?, ?, ?)',
                (participant['game_id'], participant['id'], timestamp, beverage, float(volume_ml), float(abv_percent)),
            )
            drink_id = cursor.lastrowid

    return {
        'id': drink_id,
        'game_id': participant['game_id'],
        'participant_name': participant_name,
        'beverage': beverage,
        'volume_ml': float(volume_ml),
        'abv_percent': float(abv_percent),
        'timestamp': timestamp,
    }


def get_rankings() -> list[dict[str, Any]]:
    rows = list_participants()
    game_id = get_current_game_id()
    results: list[dict[str, Any]] = []

    for row in rows:
        total_volume = 0.0
        total_abv = 0.0
        with get_connection() as conn:
            if is_postgres():
                drinks = conn.execute(
                    'SELECT volume_ml, abv_percent FROM drinks WHERE game_id = %s AND participant_id = %s ORDER BY timestamp ASC',
                    (game_id, row['id']),
                ).fetchall()
            else:
                drinks = conn.execute(
                    'SELECT volume_ml, abv_percent FROM drinks WHERE game_id = ? AND participant_id = ? ORDER BY timestamp ASC',
                    (game_id, row['id']),
                ).fetchall()

        for drink in drinks:
            volume_ml = float(drink['volume_ml'])
            abv_percent = float(drink['abv_percent'])
            total_volume += volume_ml
            total_abv += volume_ml * (abv_percent / 100.0) * 0.789

        total_volume_l = total_volume / 1000.0
        alcohol_l = total_abv / 1000.0
        weight_kg = float(row['weight_kg'])
        alcohol_per_kg = (alcohol_l / weight_kg) if weight_kg else 0.0

        results.append({
            'participant_id': row['id'],
            'game_id': game_id,
            'name': row['name'],
            'team': row['team_name'],
            'team_id': row['team_id'],
            'weight_kg': weight_kg,
            'arrival_time': row['arrival_time'],
            'total_volume_l': round(total_volume_l, 3),
            'alcohol_amount_l': round(alcohol_l, 3),
            'alcohol_per_kg': round(alcohol_per_kg, 4),
        })

    return sorted(results, key=lambda x: x['total_volume_l'], reverse=True)


def get_team_standings() -> list[dict[str, Any]]:
    participants = get_rankings()
    grouped: dict[str, list[dict[str, Any]]] = {}
    for participant in participants:
        grouped.setdefault(participant['team'], []).append(participant)

    rows: list[dict[str, Any]] = []
    for team_name, members in grouped.items():
        rows.append({
            'team': team_name,
            'members': [member['name'] for member in members],
            'total_volume_l': round(sum(member['total_volume_l'] for member in members), 3),
            'total_alcohol_l': round(sum(member['alcohol_amount_l'] for member in members), 3),
        })

    return sorted(rows, key=lambda row: row['total_alcohol_l'], reverse=True)


def get_timeline() -> list[dict[str, Any]]:
    game_id = get_current_game_id()
    participants = list_participants()
    with get_connection() as conn:
        if is_postgres():
            rows = conn.execute(
                '''
                SELECT participant_id, timestamp, volume_ml, abv_percent
                FROM drinks
                WHERE game_id = %s
                ORDER BY timestamp ASC
                ''',
                (game_id,),
            ).fetchall()
        else:
            rows = conn.execute(
                '''
                SELECT participant_id, timestamp, volume_ml, abv_percent
                FROM drinks
                WHERE game_id = ?
                ORDER BY timestamp ASC
                ''',
                (game_id,),
            ).fetchall()

    points: dict[str, dict[str, float]] = {}
    for row in rows:
        ts = row['timestamp'][:16]
        points.setdefault(ts, {})
        name = next((p['name'] for p in participants if p['id'] == row['participant_id']), 'Unknown')
        volume = float(row['volume_ml']) / 1000.0
        points[ts].setdefault(name, 0.0)
        points[ts][name] += volume

    timeline: list[dict[str, Any]] = []
    labels = sorted(points.keys())
    for label in labels:
        item = {'timestamp': label}
        for participant in participants:
            item[participant['name']] = round(sum(
                value
                for stamp, accum in points.items()
                if stamp <= label
                for name, value in accum.items()
                if name == participant['name']
            ), 3)
        timeline.append(item)

    return timeline


def reset_game() -> None:
    game_id = get_current_game_id()
    with get_connection() as conn:
        if is_postgres():
            conn.execute('DELETE FROM drinks WHERE game_id = %s', (game_id,))
            conn.execute('DELETE FROM participants WHERE game_id = %s', (game_id,))
            conn.execute('DELETE FROM teams WHERE game_id = %s', (game_id,))
        else:
            conn.execute('DELETE FROM drinks WHERE game_id = ?', (game_id,))
            conn.execute('DELETE FROM participants WHERE game_id = ?', (game_id,))
            conn.execute('DELETE FROM teams WHERE game_id = ?', (game_id,))
            conn.execute('DELETE FROM sqlite_sequence WHERE name IN ("teams", "participants", "drinks")')

    create_game(f'Game {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")}')


def get_summary() -> dict[str, Any]:
    rankings = get_rankings()
    teams = get_team_standings()
    payload = {
        'title': 'ÖDT Tracker 2025',
        'leader': rankings[0]['name'] if rankings else None,
        'team_leader': teams[0]['team'] if teams else None,
        'participant_count': len(rankings),
        'team_count': len(teams),
        'top_total_volume_l': rankings[0]['total_volume_l'] if rankings else 0.0,
        'top_alcohol_l': rankings[0]['alcohol_amount_l'] if rankings else 0.0,
    }

    return payload


def table_columns(table_name: str) -> set[str]:
    with get_connection() as conn:
        if is_postgres():
            rows = conn.execute(
                '''
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = %s
                ''',
                (table_name,),
            ).fetchall()
            return {row['column_name'] for row in rows}

        rows = conn.execute(f'PRAGMA table_info({table_name})').fetchall()
        return {row['name'] for row in rows}


def table_exists(table_name: str) -> bool:
    with get_connection() as conn:
        if is_postgres():
            row = conn.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
                (table_name,),
            ).fetchone()
            return row is not None

        row = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
            (table_name,),
        ).fetchone()
        return row is not None


def migrate_legacy_schema() -> None:
    if not table_exists('teams') or not table_exists('participants') or not table_exists('drinks'):
        return

    team_columns = table_columns('teams')
    participant_columns = table_columns('participants')
    drink_columns = table_columns('drinks')

    if 'game_id' not in team_columns or 'game_id' not in participant_columns or 'game_id' not in drink_columns:
        with get_connection() as conn:
            conn.execute('DROP TABLE IF EXISTS drinks')
            conn.execute('DROP TABLE IF EXISTS participants')
            conn.execute('DROP TABLE IF EXISTS teams')
            if table_exists('games'):
                conn.execute('DELETE FROM games')


def list_games() -> list[dict[str, Any]]:
    current_game_id = get_current_game_id()
    with get_connection() as conn:
        if is_postgres():
            rows = conn.execute(
                '''
                SELECT g.id, g.name, g.created_at,
                       COUNT(DISTINCT p.id) AS participant_count,
                       COUNT(DISTINCT d.id) AS drink_count
                FROM games g
                LEFT JOIN participants p ON p.game_id = g.id
                LEFT JOIN drinks d ON d.game_id = g.id AND d.participant_id = p.id
                GROUP BY g.id, g.name, g.created_at
                ORDER BY g.id DESC
                ''',
            ).fetchall()
        else:
            rows = conn.execute(
                '''
                SELECT g.id, g.name, g.created_at,
                       COUNT(DISTINCT p.id) AS participant_count,
                       COUNT(DISTINCT d.id) AS drink_count
                FROM games g
                LEFT JOIN participants p ON p.game_id = g.id
                LEFT JOIN drinks d ON d.game_id = g.id AND d.participant_id = p.id
                GROUP BY g.id, g.name, g.created_at
                ORDER BY g.id DESC
                '''
            ).fetchall()

        games = [_serialize_row(row) for row in rows]
        for game in games:
            game['is_current'] = int(game['id']) == int(current_game_id)
        return games


def get_game_summary(game_id: int) -> dict[str, Any]:
    with get_connection() as conn:
        if is_postgres():
            game = conn.execute('SELECT * FROM games WHERE id = %s', (game_id,)).fetchone()
            participants = conn.execute('SELECT * FROM participants WHERE game_id = %s', (game_id,)).fetchall()
            drinks = conn.execute('SELECT * FROM drinks WHERE game_id = %s', (game_id,)).fetchall()
        else:
            game = conn.execute('SELECT * FROM games WHERE id = ?', (game_id,)).fetchone()
            participants = conn.execute('SELECT * FROM participants WHERE game_id = ?', (game_id,)).fetchall()
            drinks = conn.execute('SELECT * FROM drinks WHERE game_id = ?', (game_id,)).fetchall()

    if game is None:
        raise ValueError(f'Game not found: {game_id}')

    participant_count = len(participants)
    drink_count = len(drinks)
    total_volume = sum(float(drink['volume_ml']) for drink in drinks)
    total_abv = sum(float(drink['volume_ml']) * (float(drink['abv_percent']) / 100.0) * 0.789 for drink in drinks)

    return {
        'id': game_id,
        'name': game['name'],
        'created_at': game['created_at'],
        'participant_count': participant_count,
        'drink_count': drink_count,
        'total_volume_l': total_volume / 1000.0,
        'total_alcohol_l': total_abv / 1000.0,
    }
